baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'   # will show in the Browser Tab
theme = 'hugo-sewing'
DefaultContentLanguage = "en"   # Theme's display language, supports: en, zh
footnotereturnlinkcontents = "↩"
pygmentsuseclasses = true 
staticDir = ["static"]
#enableGitInfo = true
disableKinds = ["GitInfo"]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
[[menu.main]]
    name = "Project"
    url = "/project/"
    weight = 3
[[menu.main]]
    name = "Publication"
    url = "/publication/"
    weight = 4
[[menu.main]]
    name = "People"
    url = "/people/"
    weight = 5
[[menu.main]]
    name = "Memos"
    url = "/memos/"
    weight = 6
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 7
[[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 8
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 9

[markup.goldmark.renderer]
unsafe= true

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[params]
    authorName = "Author Name"   # will show in the copyright
    enableTheme = true   # whether to display Theme information
    enableVisitor = true   # whether to display visitor information
    enableUpdated = false   # whether to display updating date information
    enableMemo = true   # whether to display memos
    enableGiscus = true   # whether to display comment in blog and contact
    enableimgloop = true
    toc = true   # whether to display table of contents in blog

    [permalinks]
        blog = "/blog/:year/:month/:slug/"

    [params.Theme]
        url = "https://github.com/HaiyanKong/hugo-sewing"
        name = "Hugo-Sewing"

    [params.visitor]
        src = "//rf.revolvermaps.com/0/0/9.js?i=5xu1925e9lo&amp"

    [params.memo]
        memos = "https://s.dusays.com/"
        limit = "10"
        creatorId = "123"
        domId = "#bber"
        twiEnv = ""  # twikoo，default https://metk.edui.fun/

    [params.giscus]  # see https://giscus.app/
        data_repo="HaiyanKong/hugo-sewing-demo"
        data_repo_id="R_kgDOMChxiA"
        data_category="Announcements"
        data_category_id="DIC_kwDOMChxiM4CftLt"
        data_mapping="pathname"
        data_strict="0"
        data_reactions_enabled="1"
        data_emit_metadata="0"
        data_input_position="top"
        data_theme="noborder_light"
        data_lang="en"
        crossorigin="anonymous"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false